const {test}=require('node:test');const assert=require('node:assert/strict');const B=require('../prototype/build-search.js');
function fixture(){return {skills:[{id:1,name:'공격',kind:'weapon',maxLevel:3,ranks:[{level:1},{level:2},{level:3}]},{id:2,name:'방어',kind:'armor',maxLevel:3,ranks:[{level:1},{level:2},{level:3}]},{id:3,name:'세트',kind:'set',maxLevel:2,ranks:[{level:1,pieces:2,name:'효과Ⅰ'},{level:2,pieces:4,name:'효과Ⅱ'}]}],weapons:[{id:1,name:'무기',slots:[2],skills:{},bonuses:[],defenseBonus:0}],armor:B.PARTS.map((part,i)=>({id:i+1,name:part,part,rank:'high',slots:i===0?[1]:[],skills:{},bonuses:[3],defense:10})),decorations:[{id:1,name:'복합주',kind:'weapon',slot:2,skills:{1:2,2:1},bonuses:[]},{id:2,name:'방어주',kind:'armor',slot:1,skills:{2:1},bonuses:[]}]};}
const request=(goals,extra={})=>({weaponId:1,goals,charmMode:'none',rank:'high',minDefense:0,...extra});
test('복합 장식주의 모든 스킬을 더하고 슬롯 종류와 위치를 보존한다',()=>{const x=B.search(fixture(),{},request([{id:1,level:2},{id:2,level:2}]));assert.equal(x.partial,false);assert.equal(x.results.length,1);const r=x.results[0];assert.deepEqual(r.achieved.map(g=>g.level),[2,2]);assert.equal(new Set(r.decorations.map(p=>p.owner+':'+p.index)).size,2);assert.equal(r.decorations[0].kind,'weapon');});
test('무기 장식주를 방어구 슬롯에 넣거나 슬롯을 재사용하지 않는다',()=>{const d=fixture();d.weapons[0].slots=[];d.armor[0].slots=[3];assert.equal(B.search(d,{},request([{id:1,level:1}])).results.length,0);d.weapons[0].slots=[1];assert.equal(B.search(d,{},request([{id:1,level:1}])).results.length,0);d.weapons[0].slots=[2];assert.equal(B.search(d,{},request([{id:1,level:3}])).results.length,0);});
test('세트 효과는 부위 수로 발동하며 최소 방어력을 지킨다',()=>{let d=fixture();assert.equal(B.search(d,{},request([{id:3,level:2}])).results[0].achieved[0].pieces,5);d.armor.slice(2).forEach(a=>a.bonuses=[]);assert.equal(B.search(d,{},request([{id:3,level:2}])).results.length,0);assert.equal(B.search(d,{},request([{id:3,level:1}],{minDefense:51})).results.length,0);});
test('보유 호석의 스킬과 타입별 슬롯을 사용한다',()=>{const d=fixture(),records=[{skills:[{name:'공격',level:3}],weaponSlots:[],armorSlots:[]}];const r=B.search(d,{groups:[],recipes:[]},request([{id:1,level:3}],{charmMode:'owned',records}));assert.equal(r.results[0].charmOwned,true);});
test('탐색 제한을 완료나 불가능으로 보고하지 않는다',()=>{const x=B.search(fixture(),{},request([{id:3,level:1}]),()=>{},{maxNodes:0});assert.equal(x.partial,true);assert.equal(x.reason,'node-limit');assert.throws(()=>B.validateRequest(fixture(),request([{id:1,level:4}])));});
test('대표 장비 축소가 장식주로 가능한 조합을 없애지 않는다',()=>{const d=fixture();d.armor.push({...d.armor[0],id:99,slots:[2,1],defense:11});const x=B.search(d,{},request([{id:2,level:3}]));assert.ok(x.results.length);assert.equal(x.results[0].armor[0].id,99);});
test('장비 스냅샷 참조와 세트 문턱이 일관된다',()=>{const d=require('../prototype/data/equipment-snapshot.json'),ids=new Set(d.skills.map(s=>s.id));assert.match(d.apiImportVersion,/2026-/);for(const a of [...d.armor,...d.weapons,...d.decorations]){assert.ok(a.slots===undefined||a.slots.every(n=>n>=1&&n<=3));for(const id of Object.keys(a.skills))assert.ok(ids.has(Number(id)));for(const id of a.bonuses)assert.ok(ids.has(id));}for(const s of d.skills.filter(s=>['set','group'].includes(s.kind)))for(const r of s.ranks)assert.ok(r.pieces>0);});
test('작은 장비 공간에서 독립 전수 조합과 대표 검색의 가능 판정이 같다',()=>{for(let need=1;need<=3;need++){const d=fixture();d.decorations=[];d.armor.forEach((a,i)=>{a.skills={1:i%2};a.slots=[];});for(const a of [...d.armor])d.armor.push({...a,id:a.id+10,skills:{2:1},defense:9});const pools=B.PARTS.map(p=>d.armor.filter(a=>a.part===p));let possible=false;function brute(n,a,b){if(n===5){if(a>=need&&b>=2)possible=true;return;}for(const item of pools[n])brute(n+1,a+(item.skills[1]||0),b+(item.skills[2]||0));}brute(0,0,0);const x=B.search(d,{},request([{id:1,level:need},{id:2,level:2}]));assert.equal(x.results.length>0,possible);}});
test('거극 아티어 시리즈·그룹 스킬을 각 1부위로 합산한다',()=>{const d=fixture();d.weapons[0].id=1172;d.skills.push({id:4,name:'그룹',kind:'group',maxLevel:1,ranks:[{level:1,pieces:3,name:'그룹 발동'}]});d.armor.forEach((a,i)=>{a.bonuses=i===0?[3,4]:i===1?[4]:[];});const q=request([{id:3,level:1},{id:4,level:1}],{weaponId:1172,weaponSeriesSkillId:3,weaponGroupSkillId:4});const x=B.search(d,{},q);assert.equal(x.results.length,1);assert.deepEqual(x.results[0].achieved.map(s=>s.pieces),[2,3]);assert.deepEqual(x.results[0].weapon.selectedBonuses.map(s=>s.id),[3,4]);assert.deepEqual(d.weapons[0].bonuses,[]);assert.equal(B.search(d,{}, {...q,weaponGroupSkillId:0}).results.length,0);assert.equal(B.search(d,{}, {...q,weaponSeriesSkillId:0}).results.length,0);});
test('제작 무기에 부여 스킬을 지정하거나 시리즈·그룹을 뒤바꾸면 거부한다',()=>{const d=fixture();assert.throws(()=>B.validateRequest(d,request([{id:3,level:1}],{weaponSeriesSkillId:3})));d.weapons[0].id=1172;assert.throws(()=>B.validateRequest(d,request([{id:3,level:1}],{weaponId:1172,weaponGroupSkillId:3})));assert.throws(()=>B.validateRequest(d,request([{id:3,level:1}],{weaponId:1172,weaponSeriesSkillId:999})));});
test('분류가 장비 스냅샷의 모든 스킬을 한 번씩 포함한다',()=>{const d=require('../prototype/data/equipment-snapshot.json'),c=require('../prototype/data/skill-categories.json');const ids=c.groups.flatMap(g=>g.ids);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids.slice().sort((a,b)=>a-b),d.skills.map(s=>s.id).sort((a,b)=>a-b));});
test('8개를 넘는 목표도 모두 검색에 반영하고 중복 목표는 거부한다',()=>{const d=fixture();d.skills=Array.from({length:10},(_,i)=>({id:i+1,name:'목표'+i,kind:'armor',maxLevel:1,ranks:[{level:1}]}));d.armor.forEach(a=>a.bonuses=[]);d.armor[0].skills=Object.fromEntries(d.skills.map(s=>[s.id,1]));d.decorations=[];const goals=d.skills.map(s=>({id:s.id,level:1}));const x=B.search(d,{},request(goals));assert.equal(x.results[0].achieved.length,10);assert.ok(x.results[0].achieved.every(g=>g.level===1));assert.throws(()=>B.validateRequest(d,request([...goals,goals[0]])));});
