const {test}=require('node:test'),assert=require('node:assert/strict'),S=require('../prototype/saved-builds.js'),B=require('../prototype/build-search.js'),d=require('../prototype/data/equipment-snapshot.json');
function entry(){const r=B.search(d,{}, {weaponId:d.weapons.find(w=>w.kind==='long-sword').id,goals:[{id:d.skills.find(s=>s.name==='납도술').id,level:3}],charmMode:'none',rank:'high',minDefense:0}).results.find(r=>r.decorations.length);return {id:'a',name:'태도 세팅',memo:'메모',created:1,build:S.snapshot(r,d,'none')};}
test('실제 검색 결과를 독립 스냅샷으로 보존하고 백업 JSON을 왕복한다',()=>{const e=entry(),x=S.validateList(JSON.parse(JSON.stringify([e])));assert.deepEqual(x,[e]);x[0].build.equipment[0].name='변경';assert.notEqual(e.build.equipment[0].name,'변경');assert.ok(e.build.skills.length>e.build.goals.length);});
test('복원 시 잘못된 슬롯 종류·크기·중복 배치를 거부한다',()=>{for(const alter of [e=>e.build.decorations.push({...e.build.decorations[0]}),e=>e.build.decorations[0].required=3,e=>e.build.decorations[0].kind=e.build.decorations[0].kind==='armor'?'weapon':'armor']){const e=entry();alter(e);assert.throws(()=>S.validateList([e]));}});
test('중복 ID·긴 메모·누락 부위·목표 미달 데이터를 복원하지 않는다',()=>{const e=entry();assert.throws(()=>S.validateList([e,e]));for(const alter of [e=>e.memo='x'.repeat(1001),e=>e.build.equipment.pop(),e=>e.build.goals[0].level=0]){const e=entry();alter(e);assert.throws(()=>S.validateList([e]));}});
test('무기 부여 스킬은 저장·JSON 복원에 남고 이전 저장은 빈 목록으로 읽는다',()=>{const e=entry();e.build.weaponBonuses=[{id:106,name:'흑식룡의 힘',kind:'set'},{id:131,name:'주인의 혼',kind:'group'}];assert.deepEqual(S.validateList(JSON.parse(JSON.stringify([e])))[0].build.weaponBonuses,e.build.weaponBonuses);delete e.build.weaponBonuses;assert.deepEqual(S.validateList([e])[0].build.weaponBonuses,[]);});
test('8개를 넘는 저장 목표를 백업 JSON에서 손실 없이 복원한다',()=>{const e=entry();e.build.goals=Array.from({length:12},(_,i)=>({name:'목표'+i,required:1,level:1}));assert.deepEqual(S.validateList(JSON.parse(JSON.stringify([e])))[0].build.goals,e.build.goals);});
test('음수 내성과 최소 조건을 복원하고 이전 세팅은 미기록으로 읽는다',()=>{const e=entry();e.build.resistances={fire:-5,water:2,thunder:0,ice:1,dragon:-2};e.build.minResistances={fire:-25,water:2};assert.deepEqual(S.validateList(JSON.parse(JSON.stringify([e])))[0].build.resistances,e.build.resistances);assert.deepEqual(S.validateList([e])[0].build.minResistances,e.build.minResistances);delete e.build.resistances;delete e.build.minResistances;assert.equal(S.validateList([e])[0].build.resistances,null);});
test('상세 메타데이터의 잘못된 레어도·스킬 종류·부위를 거부한다',()=>{for(const alter of [e=>e.build.detail.equipment[0].rarity=99,e=>e.build.detail.skills[0].kind='unknown',e=>e.build.detail.bonuses=[{id:1,name:'bad',kind:'set',parts:['unknown'],ranks:[]}]]){const e=entry();alter(e);assert.throws(()=>S.validateList([e]));}});
test('보관함과 세팅 소속을 JSON 왕복하며 빈 보관함도 보존한다',()=>{const e=entry();e.folderId='long';const folders=[{id:'long',name:'태도'},{id:'empty',name:'실험 중'}];const state=S.validateCollection(JSON.parse(JSON.stringify([e])),JSON.parse(JSON.stringify(folders)));assert.deepEqual(state,{entries:[e],folders});assert.deepEqual(S.validateCollection([entry()]).folders,[]);});
test('중복 보관함·빈 이름·없는 보관함 소속을 거부하고 미분류 이동을 허용한다',()=>{const e=entry(),f={id:'a',name:'태도'};assert.throws(()=>S.validateFolders([f,f]));assert.throws(()=>S.validateFolders([f,{id:'b',name:' 태도 '}]));assert.throws(()=>S.validateFolders([{id:'a',name:' '}])) ;e.folderId='missing';assert.throws(()=>S.validateCollection([e],[f]));e.folderId='';assert.equal(S.validateCollection([e],[]).entries[0].folderId,'');});
